<?php 
session_start();
unset($_SESSION['branch_id']);
unset($_SESSION['Logged']);
unset($_SESSION['username']);
unset($_SESSION['user_id']);
unset($_SESSION['personId']);
unset($_SESSION['admin']);
unset($_SESSION['loan_officer']);
unset($_SESSION['loans_officer']);
unset($_SESSION['branch_manager']);
unset($_SESSION['branch_credit']);
unset($_SESSION['management_credit']);
unset($_SESSION['executive_board']);
unset($_SESSION['accountant']);
unset($_SESSION['access_level']);
header("location:index.php");
?>