<?php 
require_once("Db.php");
require_once("AccessLevel.php");
require_once("Accounts.php");
require_once("AccountType.php");
require_once("Deposits.php");
require_once("Expenses.php");
require_once("ExpenseTypes.php");
require_once("LoanType.php");
require_once("Member.php");
require_once("MemberType.php");
require_once("Person.php");
require_once("Position.php"); 
require_once("SecurityType.php");
require_once("Staff.php");
require_once("WithDraws.php");
require_once("Locations.php");
require_once("Branch.php");
require_once("Loans.php");
require_once("Subscription.php");
require_once("Income.php");
require_once("Shares.php");
require_once("Nok.php");
require_once("LoanRepaymentDuration.php");
require_once("Guarantor.php");
?>